version: '3.8'

services:
  postgres-db:
    container_name: postgres17_db_container
    image: postgres:17.2-alpine
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_INITDB_ARGS=--lc-collate=ru_RU.UTF-8 --lc-ctype=ru_RU.UTF-8
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
  minio:
    container_name: minio_storage_container
    restart: always
    image: minio/minio
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    ports:
      - ${MINIO_PORT}:${MINIO_PORT}
      - ${MINIO_PORT_CONSOLE}:${MINIO_PORT_CONSOLE}
    command: server --console-address ":${MINIO_PORT_CONSOLE}" /data
  redis:
    container_name: redis_container
    restart: always
    image: redis:7.4.2-alpine
    volumes:
      - ./redis:/data
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD}
# pg - psql -U <user> -d <table>
# redis - redis-cli -a "<password>"
